{
 "title": "Memores.Wcf from ElasticSearch",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpuRate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"5\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availableVirtualMemory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"5\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "availablePhysicalMemory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"5\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "apdex",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"3\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "1s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rate1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"0\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "5s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rate1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "rate5m",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "rate15m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"0\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operationName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeStamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "metricsReportType:\"2\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "exceptionType",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timeStamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "exceptionType",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "metricsReportType: \"4\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "operationName",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "processingTime",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "field": "processingTime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "processingTime",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType:\"2\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "metricsReportType: \"4\"",
     "timeField": "timeStamp"
    }
   ]
  }
 ]
}