{
 "title": "Memores.Wcf from ElasticSearch",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests per minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rate1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"0\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rate1m",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "rate5m",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "rate15m",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"0\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Operations time",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "operationName",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "processingTime",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "min"
      },
      {
       "field": "processingTime",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "processingTime",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType:\"2\"",
     "timeField": "timeStamp"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeStamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "apdex",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "metricsReportType: \"3\"",
     "timeField": "timeStamp"
    }
   ]
  }
 ]
}